export enum ErrorCodes {
  UNAUTHORIZED = 'UNAUTHORIZED',
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
  BAD_REQUEST_VALUE_NOT_UNIQUE = 'BAD_REQUEST_VALUE_NOT_UNIQUE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  DATA_BASE_ERROR = 'DATA_BASE_ERROR',
  INVALID_UUID = 'INVALID_UUID',
}
